var firstName = prompt("Hello and Welcome! Please enter your First Name:")
var lastName = prompt("Enter your Last Name")
var age = prompt("How old are you?")
var height = prompt("How tall are you in cm?")
var pet = prompt("What is the name of your pet?")
alert("Thank you so much for the information!")
